steps:
  # Step 1: Configure Docker to authenticate with Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Configure Docker to authenticate with Artifact Registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker europe-docker.pkg.dev

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build the Docker image'
    args: [
      'build', '-t', 'europe-docker.pkg.dev/glb-fs-wgh-app-dev/fs-3-15-registry-dev-testing/cloud-cicd-github:$COMMIT_SHA', '.'
    ]

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push the Docker image to Artifact Registry'
    args: [
      'push', 'europe-docker.pkg.dev/glb-fs-wgh-app-dev/fs-3-15-registry-dev-testing/cloud-cicd-github:$COMMIT_SHA'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fs-3-15-cloud-cid-github'               # Name of your Cloud Run service
      - '--image'
      - 'europe-docker.pkg.dev/glb-fs-wgh-app-dev/fs-3-15-registry-dev-testing/cloud-cicd-github:$COMMIT_SHA'
      - '--region'
      - 'europe-west3'          # Replace with your desired region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Allow unauthenticated access
      - '--port=8080'
      - '--service-account=sa-wl-main@glb-fs-wgh-app-dev.iam.gserviceaccount.com'
      - '--min-instances=1'
      - '--vpc-connector=projects/glb-fs-wgh-app-dev/locations/europe-west3/connectors/vpc-con'
      - '--vpc-egress=all-traffic'
      - '--ingress=internal-and-cloud-load-balancing'

  # 5. Clone the Devai CLI from the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/GoogleCloudPlatform/genai-for-developers.git']

  # 6. Change directory to the devai-cli folder
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: ['-c', 'cd genai-for-developers/devai-cli']

  # 7. Run the Devai CLI (make sure it's executable)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: ['-c', 'chmod +x devai && ./devai review testcoverage -c ./src']

# Define images that are built and pushed
images:
  - 'europe-docker.pkg.dev/glb-fs-wgh-app-dev/fs-3-15-registry-dev-testing/cloud-cicd-github:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
