steps:
  # Step 1: Configure Docker to authenticate with Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Configure Docker to authenticate with Artifact Registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build the Docker image'
    args: [
      'build', '-t', 'us-central1-docker.pkg.dev/beaming-botany-437905-u5/my-docker-repo/cicd:$COMMIT_SHA', '.'
    ]

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push the Docker image to Artifact Registry'
    args: [
      'push', 'us-central1-docker.pkg.dev/beaming-botany-437905-u5/my-docker-repo/cicd:$COMMIT_SHA'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-app'               # Name of your Cloud Run service
      - '--image'
      - 'us-central1-docker.pkg.dev/beaming-botany-437905-u5/my-docker-repo/cicd:$COMMIT_SHA'
      - '--region'
      - 'us-central1'          # Replace with your desired region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Allow unauthenticated access

      # 1. Clone the Devai CLI from the GitHub repository
  - name: 'gcr.io/cloud-builders/git'
    args: [ 'clone', 'https://github.com/GoogleCloudPlatform/genai-for-developers.git' ]

      # 2. Check if the repo was cloned successfully
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: [ '-c', 'echo "Listing contents of cloned repo:" && ls -l && ls -l genai-for-developers' ]

      # 3. Change directory to the devai-cli folder and check contents
  - name: 'gcr.io/cloud-builders/docker'
   entrypoint: '/bin/sh'
   args: [ '-c', 'cd genai-for-developers/devai-cli && echo "Listing contents of devai-cli:" && ls -l' ]

   # 4. Make the devai file executable and verify permissions
   - name: 'gcr.io/cloud-builders/docker'
      entrypoint: '/bin/sh'
      args: [ '-c', 'chmod +x genai-for-developers/devai-cli/devai && echo "Checking permissions:" && ls -l genai-for-developers/devai-cli/devai' ]

      # 5. Run Devai CLI test coverage command (add echo for clarity)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: '/bin/sh'
    args: [ '-c', 'echo "Running Devai testcoverage command" && ./genai-for-developers/devai-cli/devai review testcoverage -c ./src' ]

# Define images that are built and pushed
images:
  - 'us-central1-docker.pkg.dev/beaming-botany-437905-u5/my-docker-repo/cicd:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
