steps:
  # Step 1: Configure Docker to authenticate with Artifact Registry
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Configure Docker to authenticate with Artifact Registry'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev

  # Step 2: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build the Docker image'
    args: [
      'build', '-t', 'us-central1-docker.pkg.dev/beaming-botany-437905-u5/my-docker-repo/cicd:$COMMIT_SHA', '.'
    ]

  # Step 3: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push the Docker image to Artifact Registry'
    args: [
      'push', 'us-central1-docker.pkg.dev/beaming-botany-437905-u5/my-docker-repo/cicd:$COMMIT_SHA'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy to Cloud Run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-app'               # Name of your Cloud Run service
      - '--image'
      - 'us-central1-docker.pkg.dev/beaming-botany-437905-u5/my-docker-repo/cicd:$COMMIT_SHA'
      - '--region'
      - 'us-central1'          # Replace with your desired region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'  # Allow unauthenticated access

# Define images that are built and pushed
images:
  - 'us-central1-docker.pkg.dev/beaming-botany-437905-u5/my-docker-repo/cicd:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
